"""mission evidence: the case file the runtime must fetch

Revision ID: 2f3735e775ca
Revises: eefd8b09ed70
Create Date: 2026-08-09 17:46:45.587662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3735e775ca'
down_revision: Union[str, Sequence[str], None] = 'eefd8b09ed70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'evidence')
    # ### end Alembic commands ###
