"""incidents

Revision ID: 5194ad37bdcb
Revises: 2e4f163441bb
Create Date: 2026-08-04 08:16:25.760185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5194ad37bdcb'
down_revision: Union[str, Sequence[str], None] = '2e4f163441bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('final_state', sa.String(), nullable=False),
    sa.Column('causal_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_tier', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('recommendation_accepted', sa.Boolean(), nullable=True),
    sa.Column('capability_invoked', sa.String(), nullable=True),
    sa.Column('capability_status', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.String(), nullable=True),
    sa.Column('execution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_line_id', sa.String(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('actual_cost_usd', sa.Float(), nullable=True),
    sa.Column('estimated_downtime_min', sa.Float(), nullable=True),
    sa.Column('actual_downtime_min', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_incidents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
