"""capability manifests and promotion events

Revision ID: 7f551a8ccce0
Revises: 
Create Date: 2026-08-04 00:32:37.363186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f551a8ccce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_manifests',
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('proposed_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sandbox_evidence', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('pk_capability_manifests'))
    )
    op.create_table('capability_promotion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('previous_event_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('event_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_manifests.capability_id'], name=op.f('fk_capability_promotion_events_capability_id_capability_manifests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_promotion_events')),
    sa.UniqueConstraint('capability_id', 'sequence', name=op.f('uq_capability_promotion_events_capability_id'))
    )
    # ### end Alembic commands ###

    # Intended as cheap enforcement of "append-only" — the app's DB role
    # shouldn't be able to UPDATE/DELETE a promotion event even via a bug.
    # CURRENTLY A NO-OP in local dev / this docker-compose setup: the
    # connecting role (`ados`, from POSTGRES_USER) is a Postgres superuser,
    # and superusers bypass every ACL check, REVOKE included — confirmed
    # via `SELECT rolsuper FROM pg_roles`. Left in place because it's
    # harmless and becomes real the moment a non-superuser application
    # role exists (a deliberate future least-privilege pass, not part of
    # this phase) — but don't treat this as an enforced guarantee today.
    op.execute("REVOKE UPDATE, DELETE ON capability_promotion_events FROM CURRENT_USER")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("GRANT UPDATE, DELETE ON capability_promotion_events TO CURRENT_USER")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability_promotion_events')
    op.drop_table('capability_manifests')
    # ### end Alembic commands ###
