"""capability manifest failure_count and tier_override

Revision ID: 9066dad719e7
Revises: fdc5105d8038
Create Date: 2026-08-05 23:13:51.109236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9066dad719e7'
down_revision: Union[str, Sequence[str], None] = 'fdc5105d8038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' (not in the autogenerated version) -- existing
    # rows need a real value for a NOT NULL column added after they were
    # created, same reasoning as fdc5105d8038's workdir_cleaned_up.
    op.add_column('capability_manifests', sa.Column('failure_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('capability_manifests', sa.Column('tier_override', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capability_manifests', 'tier_override')
    op.drop_column('capability_manifests', 'failure_count')
    # ### end Alembic commands ###
