"""onboarding sessions

Revision ID: 953a70bde180
Revises: bb40a10d89bd
Create Date: 2026-08-05 01:13:59.375052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '953a70bde180'
down_revision: Union[str, Sequence[str], None] = 'bb40a10d89bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('capability_id', sa.String(), nullable=True),
    sa.Column('selected_tool_name', sa.String(), nullable=True),
    sa.Column('inspection_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synthesized_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sandbox_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
