"""custom_agents

Revision ID: a1a0d1dffe13
Revises: 5194ad37bdcb
Create Date: 2026-08-04 08:23:41.023853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a0d1dffe13'
down_revision: Union[str, Sequence[str], None] = '5194ad37bdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_schema', sa.String(), nullable=False),
    sa.Column('output_schema', sa.String(), nullable=False),
    sa.Column('memory_rag', sa.Boolean(), nullable=False),
    sa.Column('target_tier', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_agents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_agents')
    # ### end Alembic commands ###
