"""llm_provider_settings

Revision ID: bb40a10d89bd
Revises: a1a0d1dffe13
Create Date: 2026-08-04 08:31:18.774082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb40a10d89bd'
down_revision: Union[str, Sequence[str], None] = 'a1a0d1dffe13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_settings',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('provider', name=op.f('pk_llm_provider_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_provider_settings')
    # ### end Alembic commands ###
