"""missions, runtime sessions, capability requests

Revision ID: eefd8b09ed70
Revises: 914fa0dfe821
Create Date: 2026-08-09 13:58:29.362663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefd8b09ed70'
down_revision: Union[str, Sequence[str], None] = '914fa0dfe821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_tier', sa.Integer(), nullable=True),
    sa.Column('risk_class', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_capability_requests'))
    )
    op.create_table('missions',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('allowed_capabilities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mission_id', name=op.f('pk_missions'))
    )
    op.create_table('runtime_sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('runtime', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_session_id', sa.String(), nullable=True),
    sa.Column('container_name', sa.String(), nullable=True),
    sa.Column('workspace_path', sa.String(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('tool_execution_count', sa.Integer(), nullable=False),
    sa.Column('capability_request_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_runtime_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_sessions')
    op.drop_table('missions')
    op.drop_table('capability_requests')
    # ### end Alembic commands ###
