"""onboarding sessions workdir cleanup marker

Revision ID: fdc5105d8038
Revises: 953a70bde180
Create Date: 2026-08-05 22:24:50.104356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc5105d8038'
down_revision: Union[str, Sequence[str], None] = '953a70bde180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('workdir_cleaned_up', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_sessions', 'workdir_cleaned_up')
    # ### end Alembic commands ###
