"""
Data models for Executive Intelligence & Strategic Reasoning (L6).
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict


class KPISummary(BaseModel):
    """Executive KPI metric summary calculated over IncidentRecord collection."""
    model_config = ConfigDict(populate_by_name=True)

    total_incidents: int = Field(..., alias="totalIncidents")
    resolved_incidents: int = Field(..., alias="resolvedIncidents")
    failed_incidents: int = Field(..., alias="failedIncidents")

    mttr_avg_minutes: float = Field(..., alias="mttrAvgMinutes", description="Mean Time To Recovery in minutes")
    mttr_median_minutes: float = Field(..., alias="mttrMedianMinutes")

    revenue_protected_usd: float = Field(..., alias="revenueProtectedUsd", description="Estimated vs actual cost savings protected")
    total_actual_cost_usd: float = Field(..., alias="totalActualCostUsd")

    autonomy_index: float = Field(..., alias="autonomyIndex", description="Percentage [0.0 - 1.0] of Tier 0 autonomous executions")
    recommendation_acceptance_rate: float = Field(
        ...,
        alias="recommendationAcceptanceRate",
        description="Percentage [0.0 - 1.0] of non-null (Tier 1/2) accepted recommendations"
    )

    tier_distribution: Dict[str, int] = Field(default_factory=dict, alias="tierDistribution")
    supplier_resilience: Dict[str, Dict[str, Any]] = Field(default_factory=dict, alias="supplierResilience")


class StrategicRecommendation(BaseModel):
    """Cross-incident strategic recommendation generated by RecommendationEngine."""
    model_config = ConfigDict(populate_by_name=True)

    recommendation_id: str = Field(..., alias="recommendationId")
    category: str = Field(..., description="SUPPLIER_REQUALIFICATION | PREDICTIVE_MAINTENANCE | AUTONOMY_PROMOTION | QUALITY_SPEC")
    title: str
    summary: str
    impact_level: str = Field(default="HIGH", description="HIGH | MEDIUM | LOW")
    estimated_annual_savings_usd: float = Field(default=0.0, alias="estimatedAnnualSavingsUsd")
    supporting_evidence: List[str] = Field(default_factory=list, alias="supportingEvidence")
    action_items: List[str] = Field(default_factory=list, alias="actionItems")


class RiskSignal(BaseModel):
    """Predictive risk signal for a plant or line."""
    model_config = ConfigDict(populate_by_name=True)

    signal_id: str = Field(..., alias="signalId")
    plant_id: str = Field(..., alias="plantId")
    line_id: str = Field(..., alias="lineId")
    risk_score: float = Field(..., description="Calculated risk score [0.0 - 1.0]")
    risk_level: str = Field(..., description="CRITICAL | ELEVATED | NORMAL")
    primary_risk_driver: str = Field(..., alias="primaryRiskDriver")
    causal_condition_id: str = Field(..., alias="causalConditionId")
    recommended_mitigation: str = Field(..., alias="recommendedMitigation")


class CopilotResponse(BaseModel):
    """Response returned by Natural Language Executive Copilot."""
    model_config = ConfigDict(populate_by_name=True)

    query: str
    answer: str
    confidence: float
    data_citations: List[Dict[str, Any]] = Field(default_factory=list, alias="dataCitations")
    visual_chart_type: Optional[str] = Field(default=None, alias="visualChartType")


class EnterpriseIntelligenceSummary(BaseModel):
    """High-level business intelligence summary for C-suite and executives."""
    model_config = ConfigDict(populate_by_name=True)

    revenue_protected_usd: float = Field(..., alias="revenueProtectedUsd")
    total_actual_cost_usd: float = Field(..., alias="totalActualCostUsd")
    mttr_avg_minutes: float = Field(..., alias="mttrAvgMinutes")
    autonomy_index: float = Field(..., alias="autonomyIndex")
    recommendation_acceptance_rate: float = Field(..., alias="recommendationAcceptanceRate")
    supplier_risk_resilience: Dict[str, Dict[str, Any]] = Field(default_factory=dict, alias="supplierRiskResilience")
    strategic_recommendations_count: int = Field(default=0, alias="strategicRecommendationsCount")
    top_plant_risk_driver: str = Field(default="None", alias="topPlantRiskDriver")


class OperationalIntelligenceSummary(BaseModel):
    """Granular operational telemetry summary for plant managers & operations engineers."""
    model_config = ConfigDict(populate_by_name=True)

    total_agent_invocations: int = Field(..., alias="totalAgentInvocations")
    agent_failures_count: int = Field(..., alias="agentFailuresCount")
    agent_failure_rate: float = Field(..., alias="agentFailureRate")
    queue_depth: int = Field(..., alias="queueDepth", description="Pending approval queue depth")
    avg_workflow_latency_ms: float = Field(..., alias="avgWorkflowLatencyMs")
    total_connector_calls: int = Field(..., alias="totalConnectorCalls")
    connector_failures_count: int = Field(..., alias="connectorFailuresCount")
    inventory_locks_count: int = Field(..., alias="inventoryLocksCount")
    active_soft_reservations: List[Dict[str, Any]] = Field(default_factory=list, alias="activeSoftReservations")
    agent_health_breakdown: Dict[str, Dict[str, Any]] = Field(default_factory=dict, alias="agentHealthBreakdown")


class ExecutiveIntelligenceOverview(BaseModel):
    """Combined executive overview hosting both Enterprise and Operational Intelligence tiers."""
    model_config = ConfigDict(populate_by_name=True)

    enterprise: EnterpriseIntelligenceSummary
    operational: OperationalIntelligenceSummary
